### ISSUE TITLE
reloadData卡顿

### ISSUE THREAD

**Issue by wangchun0129** [stackhou/YJBannerViewOC#2]
同一页面中，更换图片的数据源时，图片有卡在一般的情况。

**Comment by stackhou** [comment]
当页面切换或者数据源更改的情况下，会出现卡屏的现象，有相关API(- (void)adjustBannerViewWhenViewWillAppear;) 这个API 使用者自己调用可以解决这两个问题；如果数据源更新后需要 reloadData ，您的问题是reloadData后卡屏了吗？我认为不会，reloadData是数据重新加载，和数据源修改不修改没有关系，第一次reloadData和第二次reloadData都一样，都是对当前数据源reloadData，如果没有解决问题，及时反馈，我会及时修复，谢谢

**Comment by stackhou** [comment]
发现数据源个数在减少的时候有卡屏现象，特别是只有一张时，2.3.5以上版本已经修复
